FROM ruby:2.7.1

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    && curl -sL https://deb.nodesource.com/setup_12.x | bash \
    && apt-get install nodejs -y

RUN npm install -g yarn

ENV HOME_PATH /app

RUN mkdir $HOME_PATH

WORKDIR $HOME_PATH

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

RUN /app/bin/webpack

EXPOSE 3000