version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-RAILS
    command: ['./rails.sh']
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
      PG_PASS: password
      PG_USER: congnt
      PG_DB: demo_development

  db:
    image: postgres:10.6-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER:     congnt
      POSTGRES_DATABASE: demo_development
      POSTGRES_ROOT_PASSWORD: password

  web:
    image: nginx
    command: nginx -g 'daemon off;'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

volumes:
  db-data:
    driver: local
  bundle:
    driver: local