default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: congnt
  password: password
  pool: 5
development:
  <<: *default
  database: demo_development

production:
  <<: *default
  database: ENV['PG_DB']
  username: ENV['PG_USER']
  database: ENV['PG_PASS']

test:
  <<: *default
  database: test_development
